service: metric-lambda
frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs18.x
  region: me-central-1
  # change region whenever you deploy, and deploy to all regions! run: serverless deploy --aws-profile wards-me
  # eu-central-1
  # eu-west-1
  # ap-southeast-2
  # us-west-1
  # me-central-1

  environment:
    # This (REGION) is no longer needed/used
    REGION: 'eu-central-1'
    TIMESCALE_USER: 'wards'
    TIMESCALE_DB: 'postgres'
    TIMESCALE_PASSWORD: 'As751L4Tl3P25iZNI2yVY7wr'
    TIMESCALE_HOST: 'ec2-3-70-206-94.eu-central-1.compute.amazonaws.com'
    POSTGRES_USER: 'wardsprod'
    POSTGRES_DB: 'postgres'
    POSTGRES_PASSWORD: '02hkM2EpHYFeBvZCkvea'
    POSTGRES_HOST: 'wards-prod.c1kcykenvknf.eu-central-1.rds.amazonaws.com'
    ACTIVE_PROFILE: 'production'
    ACCESS_KEY_ID: "AKIAVUHZY32GABKXCHVY"
    ACCESS_KEY: "8gYrMogrU9sQPsYxZdbgMLV1RroXYnLW1Pnu1tXC"

functions:
  producer:
    timeout: 120
    handler: src/functions/processHealthMetric.run
    events:
      - sqs:
          arn: arn:aws:sqs:${self:provider.region}:387070877324:PROD_METRIC_HEALTH_CHECK
          batchSize: 10
          functionResponseType: ReportBatchItemFailures

plugins:
  - serverless-lift
  - serverless-plugin-typescript
