service: metric-lambda
frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs18.x

constructs:
  jobs:
    type: queue
    worker:
      handler: index.consumer

functions:
  producer:
    handler: src/functions/processHealthMetric
    events:
      - sqs:
          arn: arn:aws:sqs:eu-central-1:923494038643:PROD_METRIC_HEALTH_CHECK
          batchSize: 10
          maximumBatchingWindow: 60
          functionResponseType: ReportBatchItemFailures


plugins:
  - serverless-lift
  - serverless-plugin-typescript
