service: metric-lambda
frameworkVersion: '3'

# Run scripts to deploy to every region (modify your profile name)
# serverless deploy --region eu-central-1 --aws-profile wards-me
# serverless deploy --region eu-west-1 --aws-profile wards-me
# serverless deploy --region ap-southeast-2 --aws-profile wards-me
# serverless deploy --region us-west-1 --aws-profile wards-me
# serverless deploy --region me-central-1 --aws-profile wards-me

provider:
  name: aws
  runtime: nodejs18.x
  environment:
    # This (REGION) is no longer needed/used
    REGION: 'eu-central-1'
    TIMESCALE_USER: 'wards'
    TIMESCALE_DB: 'postgres'
    TIMESCALE_PASSWORD: 'As751L4Tl3P25iZNI2yVY7wr'
    TIMESCALE_HOST: 'ec2-3-70-206-94.eu-central-1.compute.amazonaws.com'
    POSTGRES_USER: 'wardsprod'
    POSTGRES_DB: 'postgres'
    POSTGRES_PASSWORD: '02hkM2EpHYFeBvZCkvea'
    POSTGRES_HOST: 'wards-prod.c1kcykenvknf.eu-central-1.rds.amazonaws.com'
    ACTIVE_PROFILE: 'production'

functions:
  producer:
    handler: src/functions/processHealthMetric.run
    events:
      - sqs:
          arn: arn:aws:sqs:${self:provider.region}:387070877324:PROD_METRIC_HEALTH_CHECK
          batchSize: 10
          functionResponseType: ReportBatchItemFailures

plugins:
  - serverless-lift
  - serverless-plugin-typescript
